### ISSUE TITLE
2.18 breaks typedef redefinitions

### ISSUE THREAD

**Issue by viblo** [eliben/pycparser#200]
The recent release 2.18 of pycparser breaks Pymunk as seen in this issue: https://github.com/viblo/pymunk/issues/118

I have committed a fix to Pymunk, but thought it could be good to leave a reference here in case this backwards incompatible change was unintended or breaks other things.

**Comment by eliben** [comment]
Can you narrow it down to a minimal piece of code that fails w/ 2.18 and succeds w/ 2.17?

**Comment by viblo** [comment]
This one breaks in 2.18 but works in 2.17:

```
>>> from cffi import FFI
>>> ffi = FFI()
>>> ffi.cdef("typedef void (*f)(void *data);")
>>> ffi.callback("typedef void (*f)(void *data)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\cffi\api.py", line 374, in callback
    cdecl = self._typeof(cdecl, consider_function_as_funcptr=True)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 169, in _typeof
    result = self._typeof_locked(cdecl)
  File "C:\Python27\lib\site-packages\cffi\api.py", line 154, in _typeof_locked
    type = self._parser.parse_type(cdecl)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 461, in parse_type
    return self.parse_type_and_quals(cdecl)[0]
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 464, in parse_type_and_quals
    ast, macros = self._parse('void __dummy(\n%s\n);' % cdecl)[:2]
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 271, in _parse
    self.convert_pycparser_error(e, csource)
  File "C:\Python27\lib\site-packages\cffi\cparser.py", line 300, in convert_pycparser_error
    raise CDefError(msg)
cffi.error.CDefError: cannot parse "typedef void (*f)(void *data)"
:4:16: before: f
```

**Comment by eliben** [comment]
```
$ cat /tmp/3.c
typedef void (*f)(void *data);
typedef void (*f)(void *data);
```

This file parses just fine in pycparser 2.18; So I guess I'm not sure what cffi is doing here with the different calls.

**Comment by gevak** [comment]
cffi eventually tries to pass the following file to pycparser:
```
typedef int f;
void __dummy(
typedef void (*f)(void *data)
);
```

If I'm not mistaken, you will find that it doesn't work in 2.18 but it did work in 2.17.

**Comment by eliben** [comment]
@gevak  that doesn't appear to be valid C at all... is that a typedef inside a function declaration?

**Comment by gevak** [comment]
I am not affiliated with the cffi package and I did not look into why this is the code that cffi passes to pycparser, but it is.
I tested it, and I'm getting an error running this exact code with pycparser==2.18:
```
import pycparser
p = pycparser.c_parser.CParser()
p.parse("""typedef int f;
void __dummy(
typedef void (*f)(void *data)
);""")
```
while the same code works and returns a valid object when I run it with pycparser==2.17.

If this change of behavior was intended, I don't have much more to say.
Do notice that the following similar code works on both versions (notice the **f2**):
```
import pycparser
p = pycparser.c_parser.CParser()
p.parse("""typedef int f2;
void __dummy(
typedef void (*f)(void *data)
);""")
```

**Comment by eliben** [comment]
@gevak it's conceivable that pycparser was parsing this incorrect code by mistake, and this stopped in 2.18 due to some changes in how custom types are handled. In general, pycparser may occasionally succeed to parse an invalid piece of code. 

Note:

$ cat /tmp/3.c

```
typedef int f2;
void __dummy(
    typedef void (*f)(void *data)
    );
```
```
$ gcc -std=c99 -c /tmp/3.c
/tmp/3.c:4:20: error: storage class specified for parameter ‘f’
     typedef void (*f)(void *data)
```
               
Thanks for the report anyway!
