### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding' while run both using_gcc_E_libc.py and using_cpp_libc.py

### ISSUE THREAD

**Issue by BraveY** [eliben/pycparser#296]
i could run c-to-c.py succesfully, but when i run using_gcc_E_libc.py and using_cpp_libc.py i got same error:TypeError: __init__() got an unexpected keyword argument 'encoding'.
1. when i run using_cpp_libc.py in root directory i got :
```
root@hw103:/home/yky/pycparser/pycparser# python examples/using_cpp_libc.py 
Traceback (most recent call last):
  File "examples/using_cpp_libc.py", line 29, in <module>
    cpp_args=r'-Iutils/fake_libc_include')
  File "./pycparser/__init__.py", line 89, in parse_file
    text = preprocess_file(filename, cpp_path, cpp_args, encoding)
  File "./pycparser/__init__.py", line 45, in preprocess_file
    text = check_output(path_list, universal_newlines=True, encoding=encoding)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
2.  when i run using_gcc_E_libc.py in root directory i got :
```
root@hw103:/home/yky/pycparser/pycparser# python examples/using_gcc_E_libc.py 
Traceback (most recent call last):
  File "examples/using_gcc_E_libc.py", line 29, in <module>
    cpp_args=['-E', r'-Iutils/fake_libc_include'])
  File "./pycparser/__init__.py", line 89, in parse_file
    text = preprocess_file(filename, cpp_path, cpp_args, encoding)
  File "./pycparser/__init__.py", line 45, in preprocess_file
    text = check_output(path_list, universal_newlines=True, encoding=encoding)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```
3. information of cpp  and gcc in my computer
```
root@hw103:/home/yky/pycparser/pycparser# which cpp
/usr/bin/cpp
root@hw103:/home/yky/pycparser/pycparser# cpp --version
cpp (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

````
root@hw103:/home/yky/pycparser/pycparser# which gcc 
/usr/bin/gcc
root@hw103:/home/yky/pycparser/pycparser# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by BraveY** [comment]
i think i have fixed this ERROR , in pycparser/__init__.py :45 , 
`text = check_output(path_list, universal_newlines=True, encoding=encoding)`  
the function check_output do not have the `encoding` argument  in python2.7,python3.5  according to the docs.(https://docs.python.org/3.5/library/subprocess.html)
so the examples do not work on python 2.7 -python 3.5 .
In my case ,the examples do not work on python2.7 except i delet `encoding=encoding` argument. And it can work on python 3.5.2.
Please add this information to readme file.,then i will close this issue.  Thanks for your amazing project. 👍 👍 👍

**Comment by eliben** [comment]
This seems to be due to #295

**Comment by eliben** [comment]
It should work now on all the supported versions, thanks the report!
