### PR TITLE
Add some "types" to zlib.h

### PR DESCRIPTION
**Pull request by thoni56**
Since `pycparser` includes a `zlib.h` some of the types defined by the real `zlib.h` is also required.

I'm not sure if the guarding #ifdef should be around the inclusion of the other fakes.

### CODE REVIEW

**Comment by thoni56** [comment]
Fixed the review comments, and also tried to mimic what is conditionally defined in zlib's `zconf.h`.

File: utils/fake_libc_include/zlib.h [hunk 1]
```diff
@@ -1,2 +1,33 @@
...
+
+typedef int uInt
+typedef int uLong
+#if !defined(__MACTYPES__)
+typedef int Byte
+#endif
+
+typedef int Bytef
+typedef int charf
+typedef inf intf
```
Comment (eliben) [inline utils/fake_libc_include/zlib.h]: Is this really `inf`?

Comment (thoni56) [reply utils/fake_libc_include/zlib.h]: Arrgh. Sorry about that, I must have been asleep when doing this. You missed all the missing semi-colons ;-)

My test runs included the standard `fake_lib` instead, which masked the updated one. With https://github.com/eliben/pycparser/pull/368/commits/9557a944b4bac002b6a1fb6532c79a25ba715a5e it compiles with `gcc` 7.4, except for a duplication of `__built_in_va_list` which is not related to `zlib.h`:

```
e$ gcc zlib.h
In file included from zlib.h:5:0:
_fake_typedefs.h:5:13: error: conflicting types for ‘__builtin_va_list’
 typedef int __builtin_va_list;
             ^~~~~~~~~~~~~~~~~
cc1: note: previous declaration of ‘__builtin_va_list’ was here
```
